from abc import ABC, abstractmethod
from typing import Any # For kwargs

class BaseLLMClient(ABC):
    """
    Abstract base class for LLM client implementations.
    Ensures that any client used with agents (e.g., ExtractorAgent)
    provides a consistent interface.
    """

    @abstractmethod
    def predict(self, prompt: str, **kwargs: Any) -> str:
        """
        Sends a prompt to the LLM and returns the generated text response.

        Args:
            prompt: The prompt string to send to the LLM.
            **kwargs: Additional keyword arguments that specific LLM clients might support
                      (e.g., temperature, max_tokens, model_name if not part of constructor).

        Returns:
            The text response generated by the LLM.
        """
        pass
